spring:
  profiles:
    active: dev

  application:
    name: 'api-gateway'

  cloud:
    config:
      uri: 'config-server'
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: ${SERVER_PORT:8765}
