spring:
  profiles:
    active: dev

  application:
    name: 'api-gateway'

  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: ${SERVER_PORT:8765}
