spring:
  application:
    name: 'user-service-api'

  data:
    mongodb:
      uri: 'mongodb+srv://${DB_USER}:${DB_PASSWORD}@clusterhelpdesk.8uaym.mongodb.net/${DB_NAME}?retryWrites=true&w=majority&appName=ClusterHelpDesk'
      auto-index-creation: true

springdoc:
  openapi:
    title: 'User Service API'
    description: 'Service responsible for user management'
    version: '1.0.0'
